# Individual keys
.keys:
  snowmankey_usb: &snowmankey_usb age1h3y9z9qx9jpkr8qgvptjlmpy9m5yx5vv0crhfwhjug50q20smc2qzncecg
  bas_dorkbones: &bas_dorkbones age1hhn93yt6fctv0t6a8wmtyrpznvtnc0hdg9z80m4dc5wtpad9kfwsqyc9le

  dorkbones: &dorkbones age1dv57l6fqyps0sdygr4c5qyt4rznycq29e3q8nrja69tzt49gwdgsvyey2x
  rpi4: &rpi4 age1gq9v2s559taw698zz502ugf707ceszy24usgqp26jqvwhsp35f8snnzgl3

# Groups
.user_keys: &user_keys
  - *snowmankey_usb
  - *bas_dorkbones

.host_keys: &host_keys
  - *dorkbones
  - *rpi4

.all_keys: &all_keys
  - *snowmankey_usb
  - *bas_dorkbones
  - *dorkbones
  - *rpi4

creation_rules:
  # networks/secrets.yml
  - path_regex: ^networks/secrets\.(yml|yaml)$
    shamir_threshold: 1
    key_groups:
      - age: *all_keys

  # users/secrets/*_secrets.yml
  - path_regex: ^users/secrets/.+_secrets\.(yml|yaml)$
    shamir_threshold: 1
    key_groups:
      - age: *all_keys

  # hosts/secrets/*_secrets.yml
  - path_regex: ^hosts/secrets/.+_secrets\.(yml|yaml)$
    key_groups:
      - age: *host_keys

  - path_regex: ^secrets\.(yml|yaml)$
    shamir_threshold: 1
    key_groups:
      - age: *all_keys
